apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ppu-device-plugin
  namespace: ppu-system
  labels:
    app: ppu-device-plugin
spec:
  selector:
    matchLabels:
      app: ppu-device-plugin
  template:
    metadata:
      labels:
        app: ppu-device-plugin
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: ppu-device-plugin
      hostNetwork: true
      containers:
      - name: ppu-device-plugin
        image: IMAGE_PLACEHOLDER
        imagePullPolicy: Always
        command:
        - ./ppu-device-plugin
        args:
        - --resource-name=alibabacloud.com/ppu
        - --device-count=16
        - --log-level=info
        - --socket-path=/var/lib/kubelet/device-plugins/
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugins
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep ppu-device-plugin | grep -v grep"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh  
            - -c
            - "ls /var/lib/kubelet/device-plugins/ppu.sock"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: device-plugins
        hostPath:
          path: /var/lib/kubelet/device-plugins
          type: Directory
      - name: dev
        hostPath:
          path: /dev
          type: Directory
      nodeSelector:
        ppu: "on"
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        effect: NoSchedule
      priorityClassName: system-node-critical